update development

diff --git a/tools/pipelines/child-ci-development.yml b/tools/pipelines/child-ci-development.yml
--- a/tools/pipelines/child-ci-development.yml
+++ b/tools/pipelines/child-ci-development.yml
@@ -11,6 +11,25 @@ setup_main:
     - cd firebase-dart-admin-auth-sdk
     - dart pub get || echo "Getting Dependencies. Continuing pipeline."
     - dart analyze > analysis_report.txt || echo "Analysis completed with warnings/errors. Check analysis_report.txt."
+     # Filter analysis output
+    - echo "Filtering for documentation issues, warnings, and errors excluding test/unit files..."
+    - grep -E "(Missing documentation for a public member|info|warning|error)" analysis_report.txt | grep -vE "^test/unit" > filtered_report.txt || echo "No relevant issues found."
+
+    # Check for responsible developers
+    - echo "Checking for responsible developers..."
+    - |
+      while IFS= read -r line; do
+        file=$(echo $line | awk -F ':' '{print $1}')
+        if [[ -n "$file" ]]; then
+          git_log=$(git log -n 1 --pretty=format:"%h" -- $file)
+          echo "File: $file - Last modified in commit: $git_log"
+          echo "Issue found: $line"
+        else
+          echo "No file information could be extracted from: $line"
+        fi
+      done < filtered_report.txt
+
+    - echo "Analysis complete. Please address the warnings above if applicable."
   artifacts:
     paths:
       - firebase-dart-admin-auth-sdk/analysis_report.txt
@@ -45,7 +64,7 @@ setup_example:
       done < filtered_report.txt
 
     - echo "Analysis complete. Please address the warnings above if applicable."
-    
+
   dependencies:
     - setup_main
   artifacts:
