chore: update required minimum version

diff --git a/tools/pipelines/child-ci-setup-pre-dev.yml b/tools/pipelines/child-ci-setup-pre-dev.yml
--- a/tools/pipelines/child-ci-setup-pre-dev.yml
+++ b/tools/pipelines/child-ci-setup-pre-dev.yml
@@ -69,7 +69,27 @@ validate_commit_messages:
   rules:
     - when: always
 
-
+validate_dart_sdk_version:
+  stage: validate
+  image: dart:stable
+  needs:
+    - validate_commit_messages
+  script:
+    - echo "Validating Dart SDK version..."
+    - cd firebase-dart-admin-auth-sdk/
+    - REQUIRED_VERSION="3.5.4"
+    - ACTUAL_VERSION=$(dart --version 2>&1 | grep -oP "(?<=Dart SDK version: )\d+\.\d+\.\d+")
+    - echo "Required Dart SDK version: $REQUIRED_VERSION"
+    - echo "Actual Dart SDK version: $ACTUAL_VERSION"
+    - |
+      if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$ACTUAL_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
+        echo "✅ Dart SDK version meets the requirement."
+      else
+        echo "❌ Dart SDK version $ACTUAL_VERSION is lower than required version $REQUIRED_VERSION."
+        exit 1
+      fi
+  rules:
+    - when: always
 
 analyze_main:
   stage: analyze
